version: '3.8'

services:
  cache:
    container_name: cache-redis
    image: redis:6.0.9-alpine
    networks:
      - caching
    ports:
      - 6379:6379
    volumes:
      - redis-caching-redis-data:/data

  postgres:
    container_name: db-postgres
    image: postgres:13.1-alpine
    networks:
      - caching
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - redis-caching-postgres-data:/var/lib/postgresql/data

networks:
  caching:


volumes:
  redis-caching-redis-data:
  redis-caching-postgres-data:
